version: "3"

services:
  app:
    ports:
      - 42002:22/tcp
      - 42000:80/tcp
      - 42004:9999/tcp
    env_file: .app
    # DWL_USER_NAME host
    # DWL_USER_PASSWD secretpassword
    # DWL_SSH_ACCESS false
    # DWL_SUDO_USER false
    # DWL_HTTP_SERVERADMIN admin@localhost
    # DWL_HTTP_SHIELD false
    # DWL_APACHEGUI false
    environment:
      COMPOSE_PROJECT_NAME: container_name
      DWL_LOCAL_LANG: 'en_US:en'
      DWL_LOCAL: 'en_US.UTF-8'
      DWL_USER_ID: 1000
      DWL_HTTP_DOCUMENTROOT: /var/www/html
      DWL_PHP_DATETIMEZONE: 'Europe/Paris'
    tty: true
    stdin_open: true
    hostname: localhost
    image: davask/d-php:7.0-a2.4-d8.x
    volumes:
      - ../volumes/home/host:/home/davask
      - ../volumes/etc/apache2/sites-available:/etc/apache2/sites-available

# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dwlhost
# docker-compose -f /home/$(whoami)/docker-images/images/app/d-php/d-php/docker-compose.yml up -d
